fields:
- label: ''
  mark_type: x_mark
  page: 8
  paper_id: S8_hispanic_Q1
  qualtrics_id: Q8.7
  regions:
    '1':
      h: 50
      w: 79
      x: 323
      y: 1103
    '2':
      h: 47
      w: 84
      x: 318
      y: 1162
  required: true
  scale:
  - 1
  - 2
  type: categorical
- label: ''
  mark_type: x_mark
  page: 8
  paper_id: S8_housing_Q1
  qualtrics_id: Q8.9
  regions:
    '1':
      h: 70
      w: 99
      x: 310
      y: 1536
    '2':
      h: 53
      w: 96
      x: 306
      y: 1604
    '3':
      h: 50
      w: 100
      x: 304
      y: 1666
  required: true
  scale:
  - 1
  - 2
  - 3
  type: categorical
- label: ''
  mark_type: x_mark
  page: 8
  paper_id: S8_income_Q1
  qualtrics_id: Q8.10
  regions:
    '1':
      h: 68
      w: 95
      x: 318
      y: 1930
    '2':
      h: 46
      w: 95
      x: 318
      y: 2005
    '3':
      h: 43
      w: 90
      x: 319
      y: 2058
    '4':
      h: 37
      w: 102
      x: 319
      y: 2104
    '5':
      h: 50
      w: 84
      x: 320
      y: 2154
    '6':
      h: 56
      w: 88
      x: 319
      y: 2213
  required: true
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  type: categorical
- paper_id: S8_race_Q1
  qualtrics_id: Q8.8
  label: ''
  type: multi_select
  mark_type: x_mark
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  page: 8
  required: true
  regions:
    '1':
      x: 1055
      y: 1065
      w: 110
      h: 30
    '2':
      x: 1055
      y: 1138
      w: 110
      h: 30
    '3':
      x: 1055
      y: 1185
      w: 110
      h: 30
    '4':
      x: 1055
      y: 1238
      w: 110
      h: 30
    '5':
      x: 1055
      y: 1284
      w: 110
      h: 30
    '6':
      x: 1055
      y: 1333
      w: 110
      h: 30
- paper_id: S1_Q1
  qualtrics_id: Q2.1_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: &id001
  - 1
  - 2
  - 3
  - 4
  page: 1
  required: true
  regions:
    '1':
      x: 1428
      y: 628
    '2':
      x: 1662
      y: 636
    '3':
      x: 1860
      y: 628
    '4':
      x: 2036
      y: 632
- paper_id: S1_Q2
  qualtrics_id: Q2.1_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1447
      y: 764
    '2':
      x: 1666
      y: 760
    '3':
      x: 1858
      y: 760
    '4':
      x: 2036
      y: 756
- paper_id: S1_Q3
  qualtrics_id: Q2.1_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1443
      y: 877
    '2':
      x: 1662
      y: 885
    '3':
      x: 1852
      y: 885
    '4':
      x: 2040
      y: 897
- paper_id: S1_Q4
  qualtrics_id: Q2.1_4
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1447
      y: 1014
    '2':
      x: 1668
      y: 1014
    '3':
      x: 1858
      y: 1018
    '4':
      x: 2040
      y: 1018
- paper_id: S1_Q5
  qualtrics_id: Q2.2_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1445
      y: 1174
    '2':
      x: 1666
      y: 1174
    '3':
      x: 1860
      y: 1185
    '4':
      x: 2044
      y: 1177
- paper_id: S1_Q6
  qualtrics_id: Q2.2_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1445
      y: 1283
    '2':
      x: 1666
      y: 1287
    '3':
      x: 1858
      y: 1287
    '4':
      x: 2042
      y: 1294
- paper_id: S1_Q7
  qualtrics_id: Q2.3_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1445
      y: 1446
    '2':
      x: 1662
      y: 1446
    '3':
      x: 1852
      y: 1446
    '4':
      x: 2038
      y: 1458
- paper_id: S1_Q8
  qualtrics_id: Q2.3_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1443
      y: 1563
    '2':
      x: 1666
      y: 1567
    '3':
      x: 1860
      y: 1560
    '4':
      x: 2040
      y: 1556
- paper_id: S1_Q9
  qualtrics_id: Q2.3_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1445
      y: 1669
    '2':
      x: 1662
      y: 1677
    '3':
      x: 1860
      y: 1677
    '4':
      x: 2040
      y: 1684
- paper_id: S1_Q10
  qualtrics_id: Q2.3_4
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id001
  page: 1
  required: true
  regions:
    '1':
      x: 1447
      y: 1774
    '2':
      x: 1664
      y: 1790
    '3':
      x: 1856
      y: 1782
    '4':
      x: 2040
      y: 1793
- paper_id: S2_Q1
  qualtrics_id: Q3.1_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: &id002
  - 1
  - 2
  - 3
  - 4
  page: 2
  required: true
  regions:
    '1':
      x: 1418
      y: 784
    '2':
      x: 1649
      y: 784
    '3':
      x: 1850
      y: 780
    '4':
      x: 2032
      y: 799
- paper_id: S2_Q2
  qualtrics_id: Q3.1_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1420
      y: 901
    '2':
      x: 1651
      y: 897
    '3':
      x: 1850
      y: 905
    '4':
      x: 2034
      y: 901
- paper_id: S2_Q3
  qualtrics_id: Q3.1_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1418
      y: 1014
    '2':
      x: 1651
      y: 1018
    '3':
      x: 1848
      y: 1018
    '4':
      x: 2032
      y: 1018
- paper_id: S2_Q4
  qualtrics_id: Q3.1_4
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1416
      y: 1131
    '2':
      x: 1651
      y: 1131
    '3':
      x: 1848
      y: 1135
    '4':
      x: 2034
      y: 1135
- paper_id: S2_Q5
  qualtrics_id: Q3.1_5
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1416
      y: 1248
    '2':
      x: 1647
      y: 1248
    '3':
      x: 1848
      y: 1248
    '4':
      x: 2032
      y: 1252
- paper_id: S2_Q6
  qualtrics_id: Q3.1_6
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1414
      y: 1369
    '2':
      x: 1647
      y: 1365
    '3':
      x: 1848
      y: 1365
    '4':
      x: 2034
      y: 1372
- paper_id: S2_Q7
  qualtrics_id: Q3.1_7
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1416
      y: 1478
    '2':
      x: 1649
      y: 1478
    '3':
      x: 1848
      y: 1482
    '4':
      x: 2029
      y: 1482
- paper_id: S2_Q8
  qualtrics_id: Q3.1_8
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id002
  page: 2
  required: true
  regions:
    '1':
      x: 1416
      y: 1591
    '2':
      x: 1647
      y: 1599
    '3':
      x: 1846
      y: 1595
    '4':
      x: 2032
      y: 1599
- paper_id: S3_Q1
  qualtrics_id: Q4.1_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: &id003
  - 1
  - 2
  - 3
  - 4
  page: 3
  required: true
  regions:
    '1':
      x: 1356
      y: 694
    '2':
      x: 1608
      y: 698
    '3':
      x: 1841
      y: 694
    '4':
      x: 2048
      y: 698
- paper_id: S3_Q2
  qualtrics_id: Q4.1_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id003
  page: 3
  required: true
  regions:
    '1':
      x: 1356
      y: 834
    '2':
      x: 1608
      y: 830
    '3':
      x: 1839
      y: 834
    '4':
      x: 2046
      y: 838
- paper_id: S3_Q3
  qualtrics_id: Q4.1_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id003
  page: 3
  required: true
  regions:
    '1':
      x: 1354
      y: 944
    '2':
      x: 1608
      y: 944
    '3':
      x: 1841
      y: 944
    '4':
      x: 2048
      y: 951
- paper_id: S3_Q4
  qualtrics_id: Q4.1_4
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id003
  page: 3
  required: true
  regions:
    '1':
      x: 1356
      y: 1053
    '2':
      x: 1610
      y: 1057
    '3':
      x: 1841
      y: 1057
    '4':
      x: 2046
      y: 1057
- paper_id: S3_Q5
  qualtrics_id: Q4.1_5
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id003
  page: 3
  required: true
  regions:
    '1':
      x: 1352
      y: 1166
    '2':
      x: 1606
      y: 1162
    '3':
      x: 1837
      y: 1170
    '4':
      x: 2048
      y: 1174
- paper_id: S4_Q1
  qualtrics_id: Q5.2_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: &id004
  - 1
  - 2
  - 3
  - 4
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 717
    '2':
      x: 1496
      y: 725
    '3':
      x: 1753
      y: 721
    '4':
      x: 1982
      y: 721
- paper_id: S4_Q2
  qualtrics_id: Q5.2_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1213
      y: 893
    '2':
      x: 1492
      y: 885
    '3':
      x: 1753
      y: 889
    '4':
      x: 1982
      y: 893
- paper_id: S4_Q3
  qualtrics_id: Q5.2_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1217
      y: 1033
    '2':
      x: 1494
      y: 1037
    '3':
      x: 1753
      y: 1037
    '4':
      x: 1982
      y: 1041
- paper_id: S4_Q4
  qualtrics_id: Q5.3_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 1279
    '2':
      x: 1492
      y: 1275
    '3':
      x: 1750
      y: 1279
    '4':
      x: 1982
      y: 1279
- paper_id: S4_Q5
  qualtrics_id: Q5.3_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 1388
    '2':
      x: 1492
      y: 1388
    '3':
      x: 1753
      y: 1388
    '4':
      x: 1980
      y: 1396
- paper_id: S4_Q6
  qualtrics_id: Q5.3_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 1505
    '2':
      x: 1494
      y: 1501
    '3':
      x: 1748
      y: 1501
    '4':
      x: 1982
      y: 1509
- paper_id: S4_Q7
  qualtrics_id: Q5.4_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 1751
    '2':
      x: 1492
      y: 1758
    '3':
      x: 1746
      y: 1751
    '4':
      x: 1980
      y: 1754
- paper_id: S4_Q8
  qualtrics_id: Q5.4_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 1899
    '2':
      x: 1494
      y: 1899
    '3':
      x: 1748
      y: 1899
    '4':
      x: 1980
      y: 1903
- paper_id: S4_Q9
  qualtrics_id: Q5.4_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 2008
    '2':
      x: 1494
      y: 2012
    '3':
      x: 1748
      y: 2012
    '4':
      x: 1980
      y: 2016
- paper_id: S4_Q10
  qualtrics_id: Q5.4_4
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1215
      y: 2121
    '2':
      x: 1492
      y: 2117
    '3':
      x: 1740
      y: 2117
    '4':
      x: 1978
      y: 2125
- paper_id: S4_Q11
  qualtrics_id: Q5.4_5
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id004
  page: 4
  required: true
  regions:
    '1':
      x: 1211
      y: 2230
    '2':
      x: 1492
      y: 2230
    '3':
      x: 1746
      y: 2234
    '4':
      x: 1978
      y: 2234
- paper_id: S5_Q1
  qualtrics_id: Q6.2_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: &id005
  - 1
  - 2
  - 3
  - 4
  page: 5
  required: true
  regions:
    '1':
      x: 1323
      y: 885
    '2':
      x: 1552
      y: 889
    '3':
      x: 1775
      y: 889
    '4':
      x: 1990
      y: 889
- paper_id: S5_Q2
  qualtrics_id: Q6.2_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1323
      y: 1033
    '2':
      x: 1548
      y: 1037
    '3':
      x: 1773
      y: 1041
    '4':
      x: 1990
      y: 1041
- paper_id: S5_Q3
  qualtrics_id: Q6.2_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1323
      y: 1162
    '2':
      x: 1550
      y: 1162
    '3':
      x: 1773
      y: 1162
    '4':
      x: 1990
      y: 1166
- paper_id: S5_Q4
  qualtrics_id: Q6.3_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1323
      y: 1357
    '2':
      x: 1550
      y: 1357
    '3':
      x: 1769
      y: 1357
    '4':
      x: 1992
      y: 1361
- paper_id: S5_Q5
  qualtrics_id: Q6.3_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1321
      y: 1466
    '2':
      x: 1550
      y: 1470
    '3':
      x: 1771
      y: 1470
    '4':
      x: 1992
      y: 1470
- paper_id: S5_Q6
  qualtrics_id: Q6.3_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1323
      y: 1599
    '2':
      x: 1550
      y: 1599
    '3':
      x: 1773
      y: 1599
    '4':
      x: 1992
      y: 1599
- paper_id: S5_Q7
  qualtrics_id: Q6.4_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1321
      y: 1844
    '2':
      x: 1548
      y: 1844
    '3':
      x: 1773
      y: 1844
    '4':
      x: 1994
      y: 1844
- paper_id: S5_Q8
  qualtrics_id: Q6.4_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1321
      y: 1969
    '2':
      x: 1550
      y: 1969
    '3':
      x: 1771
      y: 1969
    '4':
      x: 1990
      y: 1973
- paper_id: S5_Q9
  qualtrics_id: Q6.4_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1321
      y: 2078
    '2':
      x: 1548
      y: 2078
    '3':
      x: 1773
      y: 2082
    '4':
      x: 1992
      y: 2078
- paper_id: S5_Q10
  qualtrics_id: Q6.4_4
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1323
      y: 2191
    '2':
      x: 1550
      y: 2191
    '3':
      x: 1775
      y: 2183
    '4':
      x: 1994
      y: 2187
- paper_id: S5_Q11
  qualtrics_id: Q6.4_5
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id005
  page: 5
  required: true
  regions:
    '1':
      x: 1321
      y: 2304
    '2':
      x: 1546
      y: 2300
    '3':
      x: 1769
      y: 2300
    '4':
      x: 1992
      y: 2304
- paper_id: S6_Q1
  qualtrics_id: Q7.1_1
  label: ''
  type: likert
  mark_type: circled_number
  scale: &id006
  - 1
  - 2
  - 3
  - 4
  page: 6
  required: true
  regions:
    '1':
      x: 1277
      y: 1353
    '2':
      x: 1529
      y: 1357
    '3':
      x: 1784
      y: 1353
    '4':
      x: 2038
      y: 1353
- paper_id: S6_Q2
  qualtrics_id: Q7.1_2
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id006
  page: 6
  required: true
  regions:
    '1':
      x: 1275
      y: 1458
    '2':
      x: 1527
      y: 1458
    '3':
      x: 1786
      y: 1458
    '4':
      x: 2038
      y: 1462
- paper_id: S6_Q3
  qualtrics_id: Q7.1_3
  label: ''
  type: likert
  mark_type: circled_number
  scale: *id006
  page: 6
  required: true
  regions:
    '1':
      x: 1275
      y: 1567
    '2':
      x: 1529
      y: 1567
    '3':
      x: 1786
      y: 1563
    '4':
      x: 2042
      y: 1567
- paper_id: S7_area_Q1
  qualtrics_id: Q8.2
  label: ''
  type: likert
  mark_type: circled_bubble
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  page: 7
  required: true
  regions:
    '1':
      x: 453
      y: 2491
    '2':
      x: 451
      y: 2542
    '3':
      x: 448
      y: 2589
    '4':
      x: 670
      y: 2495
    '5':
      x: 672
      y: 2542
- paper_id: S7_tenure_Q1
  qualtrics_id: Q8.3
  label: ''
  type: categorical
  mark_type: circled_bubble
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  page: 7
  required: true
  regions:
    '1':
      x: 1331
      y: 2441
    '2':
      x: 1331
      y: 2491
    '3':
      x: 1331
      y: 2546
    '4':
      x: 1678
      y: 2445
    '5':
      x: 1678
      y: 2491
    '6':
      x: 1678
      y: 2542
- paper_id: S8_age_Q1
  qualtrics_id: Q8.4
  label: ''
  type: categorical
  mark_type: circled_bubble
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  page: 8
  required: true
  regions:
    '1':
      x: 418
      y: 202
    '2':
      x: 417
      y: 247
    '3':
      x: 418
      y: 299
    '4':
      x: 418
      y: 348
    '5':
      x: 698
      y: 195
    '6':
      x: 696
      y: 247
    '7':
      x: 698
      y: 299
    '8':
      x: 698
      y: 348
- paper_id: S8_gender_Q1
  qualtrics_id: Q8.5
  label: ''
  type: categorical
  mark_type: circled_bubble
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  page: 8
  required: true
  regions:
    '1':
      x: 1095
      y: 168
    '2':
      x: 1095
      y: 226
    '3':
      x: 1097
      y: 273
    '4':
      x: 1099
      y: 320
    '5':
      x: 1097
      y: 429
- paper_id: S8_edu_Q1
  qualtrics_id: Q8.6
  label: ''
  type: categorical
  mark_type: circled_bubble
  scale:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  page: 8
  required: true
  regions:
    '1':
      x: 401
      y: 632
    '2':
      x: 399
      y: 686
    '3':
      x: 401
      y: 733
    '4':
      x: 401
      y: 788
    '5':
      x: 397
      y: 834
    '6':
      x: 399
      y: 885
qualtrics:
  template: qualtrics_templates/maize_community_survey_template.xlsx
survey_id: maize_community_survey
version: 1
